version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: mern-io-server_ctr
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-5000}
      HOSTNAME: ${HOSTNAME}
      MONGO_URI: ${MONGO_URI:-mongodb://localhost:27017/exampleDatabase}
      JWT_SECRET: ${JWT_SECRET:-Ai9Kd3Jn0Nk2Tf1Nv5Vn}
      JWT_EXPIRY: ${JWT_EXPIRY:-1d}
    ports:
      - 5000:5000
